- name: Install system dependencies
  block:
    - name: Install packages
      package:
        name:
          - golang
          - make
      become: true

- name: Install operator-sdk
  become: true
  ansible.builtin.uri:
    url: https://github.com/operator-framework/operator-sdk/releases/download/v1.28.0/operator-sdk_linux_amd64
    dest: /usr/bin/operator-sdk
    mode: "755"
    status_code:
      - 200
      - 304

- name: Run make
  command: make
  loop:
    - make
    - make gen-operator-install
    - make bundle
  args:
    chdir: "{{ zuul.project.src_dir }}"

- name: Check for diff
  command: git diff
  args:
    chdir: "{{ zuul.project.src_dir }}"
  register: render_diff

- name: Abort on diff
  when:
    - render_diff.stdout
  failed_when: true
  debug:
    msg: |
      The repository content is not consistent.
      Please commit the change made after running
      make && make gen-operator-install && make bundle

      {{ render_diff.stdout }}

- name: Check cluster access
  command: kubectl cluster-info

- name: Install the CRDS
  command: make install
  args:
    chdir: "{{ zuul.project.src_dir }}"
