---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: manager-role
rules:
  - apiGroups:
      - monocle.monocle.change-metrics.io
    resources:
      - monocles
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - monocle.monocle.change-metrics.io
    resources:
      - monocles/finalizers
    verbs:
      - update
  - apiGroups:
      - monocle.monocle.change-metrics.io
    resources:
      - monocles/status
    verbs:
      - get
      - patch
      - update
