apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: monocle-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Monocle is the Schema for the monocles API
      displayName: Monocle
      kind: Monocle
      name: monocles.monocle.monocle.change-metrics.io
      version: v1alpha1
  description: Monocle Git Repos Dashboard
  displayName: Monocle Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - monocle
  - git
  - repo
  - dashboard
  links:
  - name: Monocle Operator
    url: https://monocle-operator.domain
  maturity: alpha
  provider:
    name: MonocleOperator
    url: https://github.com/change-metrics/monocle
  version: 0.0.0
