- name: Create the monocle namespace
  command: |
    kubectl create namespace monocle
    kubectl config set-context microshift --namespace=monocle

- name: Run the operator
  command: go run ./main.go
  async: 100000
  poll: 0
  args:
    chdir: "{{ zuul.project.src_dir }}"
  environment:
    WATCH_NAMESPACE: monocle
