- hosts: "{{ hostname | default('all') }}"
  roles:
    # Install deps, build and install the CRD
    - install-operator
    # Run the Monocle operator
    - run-operator
    # Claim a Monocle instance
    - claim-instance
