- hosts: "{{ hostname | default('all') }}"
  tasks:
    - name: Install system dependencies
      package:
        name:
          - make
          - golang
          - podman
      become: true

    - name: Build operator image
      shell: make container-build
      args:
        chdir: "{{ zuul.project.src_dir }}"

    - name: Login on quay.io
      shell: podman login -u="{{ quay_io_account.username }}" -p="{{ quay_io_account.password }}" quay.io
      no_log: true

    - name: Publish image
      shell: make container-push
      args:
        chdir: "{{ zuul.project.src_dir }}"
